// Package scaffold generates skeleton YAML files for design layer authoring.
// Each function returns a complete, commented YAML string suitable for redirection
// to a file and subsequent editing.
package scaffold

// Device returns a complete device atom skeleton YAML with inline documentation.
// The skeleton contains all required fields and explanatory comments.
//
// OT Domain Note: Register addresses in real PLCs are NOT contiguous arrays starting
// at zero. Real PLC programs map specific process variables to specific addresses,
// and gaps are normal and expected. The examples below model this correctly.
func Device() string {
	// PROTOTYPE-DEBT: [td-design-001] Schema version is hardcoded to "0.1".
	// Update this scaffold when schema v0.2 features are defined.
	return deviceScaffold
}

// deviceScaffold is the complete device atom skeleton template.
// It uses non-sequential register addresses with gaps to model real PLC behavior.
// See design/devices/compactlogix-l33er.yaml for a production example.
const deviceScaffold = `# Device Atom Skeleton - generated by ot-design scaffold --device
# Edit all placeholder values before use.
# See design/devices/compactlogix-l33er.yaml for a complete zero-based example.
# See design/devices/slc-500-05.yaml for a complete one-based example.
# Reference: ADR-009 D3 - Device Atom Schema v0.1

# Required: must be "0.1" for the current schema version.
schema_version: "0.1"

device:
  # Required: unique identifier, kebab-case, matches the filename without .yaml
  id: "your-device-id"
  # Required: manufacturer name (e.g., "Allen-Bradley", "Schneider Electric", "Moxa")
  vendor: "Your Vendor Name"
  # Required: specific model designation (e.g., "CompactLogix 5380 L33ER")
  model: "Your Model Name"
  # Required: one of: plc, gateway, hmi, sensor, relay, safety-controller
  category: "plc"
  # Optional: year the hardware was released (helps convey legacy vs modern)
  vintage: 2020
  # Optional: human-readable description for training context
  description: "Brief description of what this device does and why it matters for OT security"

connectivity:
  ports:
    # At least one port with at least one protocol is required.
    # For Ethernet devices (modern PLCs, HMIs):
    - type: "ethernet"
      protocols: ["modbus-tcp"]
    # For serial devices (legacy PLCs behind a gateway):
    # - type: "rs485"
    #   protocols: ["modbus-rtu"]
    # Port types: ethernet, rs485, rs232, rs422, dh485
    # Protocol examples: modbus-tcp, modbus-rtu, dh-485

  # Optional: typical round-trip latency in milliseconds.
  # Ethernet devices: 2-10ms typical. Serial devices: 20-100ms typical.
  # Serial devices have higher minimum latency (>= 10ms) due to bus arbitration.
  response_delay_ms: 10

  # Optional: timing variation (jitter) around response_delay_ms.
  response_jitter_ms: 5

  # Optional: maximum simultaneous TCP connections (serial devices: 1).
  concurrent_connections: 4

# Register capabilities define the hardware address space limits.
# These are device-wide limits -- not role-specific assignments.
# Role-specific register layouts are in register_map_variants below.
registers:
  # Required: maximum number of holding registers (4xxxx address space).
  max_holding: 256
  # Required: maximum number of coils (0xxxx address space).
  max_coils: 128
  # Optional: maximum number of input registers (3xxxx address space).
  max_input_registers: 256
  # Optional: maximum number of discrete inputs (1xxxx address space).
  max_discrete_inputs: 128

  # Required: "zero-based" or "one-based"
  # zero-based: valid addresses are 0 through (max-1). Used by most modern PLCs.
  # one-based: valid addresses are 1 through max. Used by Modicon/legacy PLCs
  #            and devices with ProSoft-style Modbus mapping modules.
  addressing: "zero-based"

  # Required: byte order for 32-bit floats stored across two consecutive registers.
  # Allen-Bradley: "big-endian" (network byte order, Modbus standard)
  # Schneider/Modicon: "little-endian" or "big-endian-byte-swap" (CDAB word order)
  # Valid values: big-endian, little-endian, big-endian-byte-swap, little-endian-byte-swap
  float_byte_order: "big-endian"

  # Optional: Modbus spec maximum is 125. Most devices support the full range.
  max_registers_per_read: 125

# Register map variants define role-specific register layouts.
# The same device type serves different roles by loading different variants.
# Each variant must stay within the register capabilities declared above.
# The environment selects a variant via register_map_variant in the placement.
register_map_variants:
  # Example variant name: use a descriptive role name (e.g., "water-intake", "mfg-line-a").
  your-variant-name:
    # Important: Real PLC register maps are NOT contiguous memory arrays.
    # Addresses reflect how the PLC program was written -- gaps are normal and expected.
    # The example below shows non-sequential addresses (1, 2, 10, 11) with a gap at 3-9.
    # This models realistic PLC programming where related variables are grouped,
    # and gaps represent registers used by other program sections or reserved for future use.
    holding:
      # Zero-based example (addresses 0 through max_holding-1):
      # - { address: 0, name: "your_register_name", unit: "%", scale_min: 0, scale_max: 100, writable: false, description: "What this register measures or controls" }
      # - { address: 1, name: "another_register", unit: "kPa", scale_min: 0, scale_max: 500, writable: false, description: "Another measurement" }
      # -- gap at addresses 2-9 is intentional (used by other program rungs) --
      # - { address: 10, name: "setpoint_value", unit: "degC", scale_min: 0, scale_max: 100, writable: true, description: "Operator setpoint (writable registers are attack surfaces)" }

      # One-based example (addresses 1 through max_holding):
      # - { address: 1, name: "your_register_name", unit: "%", scale_min: 0, scale_max: 100, writable: false, description: "What this register measures" }
      # - { address: 2, name: "another_register", unit: "A", scale_min: 0, scale_max: 30, writable: false, description: "Motor current" }
      # -- gap at addresses 3-9 is intentional --
      # - { address: 10, name: "speed_setpoint", unit: "RPM", scale_min: 0, scale_max: 1800, writable: true, description: "Speed setpoint" }

      - address: 0
        name: "your_register_name"
        description: "What this register measures or controls"
        unit: "%"           # Engineering unit (e.g., L/s, kPa, degC, %, A, GPM, PSI)
        scale_min: 0        # Value at register reading 0 (0x0000)
        scale_max: 100      # Value at register reading 32767 (0x7FFF), max for 16-bit signed
        writable: false     # true = operator can write (setpoint/command); false = read-only sensor

    coils:
      # Coils are single-bit discrete outputs.
      # true = output energized/on, false = de-energized/off.
      # Read-only coils (writable: false) report physical input states.
      - address: 0
        name: "your_coil_name"
        description: "What this coil controls or indicates"
        writable: true      # true = operator can command; false = read-only status

diagnostics:
  # Whether the device exposes a web management interface.
  web_server: false
  # Web management port (0 if web_server is false).
  web_port: 0
  # Whether the device supports SNMP polling.
  snmp: false
  # Whether the device sends syslog messages.
  syslog: false
  # Whether the device maintains an internal fault log.
  fault_log: false
  # Number of fault log entries the device retains (0 if fault_log is false).
  fault_log_depth: 0
`
