package scaffold

// Environment returns a complete environment skeleton YAML with inline documentation.
// The caller should redirect this output to a file:
//
//	ot-design scaffold --environment > design/environments/my-env/environment.yaml
func Environment() string {
	// PROTOTYPE-DEBT: [td-design-003] Schema version is hardcoded to "0.1".
	// Update this scaffold when schema v0.2 features are defined.
	return environmentScaffold
}

// environmentScaffold is the complete environment skeleton template.
// See design/environments/greenfield-water-mfg/environment.yaml for a complete example.
const environmentScaffold = `# Environment Skeleton - generated by ot-design scaffold --environment
# Save this file to: design/environments/<your-env-id>/environment.yaml
# See design/environments/greenfield-water-mfg/environment.yaml for a complete example.
# Reference: ADR-009 D5 - Environment Schema v0.1

# Required: must be "0.1" for the current schema version.
schema_version: "0.1"

environment:
  # Required: unique identifier, kebab-case, matches the directory name.
  id: "your-environment-id"
  # Optional: human-readable name for display in HMI or scenario descriptions.
  name: "Your Environment Name"
  # Optional: description for training context.
  description: "Brief description of this facility and its training purpose"

# All networks used by any placement must be listed here.
# Each ref must match a filename in design/networks/ (without .yaml extension).
# Serial buses are networks too -- list them here even though they have no IP subnet.
networks:
  - ref: "your-ethernet-network"    # e.g., wt-level1, mfg-flat
  - ref: "your-serial-bus"          # e.g., mfg-serial-bus (omit if no serial devices)

# Placements wire device atoms onto networks with specific addressing.
# Each placement ID must be unique within this environment.
# Validate using: ot-design validate design/environments/<your-env-id>/
placements:
  # Ethernet device example (direct Modbus TCP access):
  - id: "your-plc-01"
    # Required: references a file in design/devices/ (without .yaml extension).
    device: "your-device-id"
    # Required: must be listed in the networks section above.
    network: "your-ethernet-network"
    # Required for ethernet placements: IPv4 address within the network's subnet.
    ip: "10.0.0.10"
    # Required for ethernet Modbus TCP devices: port in range 5020-5039 (per CLAUDE.md).
    modbus_port: 5020
    # Optional: human-readable role description for training context.
    role: "PLC 1 - Process Control"
    # Required if device has multiple variants: selects the register map layout.
    # Must match a key in the device's register_map_variants section.
    register_map_variant: "your-variant-name"

  # Gateway device example (bridges Ethernet to serial bus):
  - id: "your-gateway-01"
    device: "your-gateway-device"
    network: "your-ethernet-network"
    ip: "10.0.0.20"
    modbus_port: 5030
    role: "Serial-to-Ethernet Gateway"
    register_map_variant: "your-gateway-variant"
    # Required for gateway-category devices: list all serial networks this gateway bridges.
    bridges:
      # from_network: always the Ethernet side (the IP network the gateway is on).
      # to_network: always the serial side (the RS-485 bus the legacy devices are on).
      - from_network: "your-ethernet-network"
        to_network: "your-serial-bus"

  # Serial device example (accessed via gateway, not directly by IP):
  - id: "your-serial-plc-01"
    device: "your-serial-device"
    network: "your-serial-bus"
    # Required for serial devices: Modbus RTU address, range 1-247.
    # Address 0 is Modbus broadcast (reserved). Addresses 248-255 are reserved.
    serial_address: 1
    # Required for serial devices: must match a placement ID of a gateway device.
    gateway: "your-gateway-01"
    role: "Line A PLC"
    register_map_variant: "your-serial-variant"
    # Note: serial devices must NOT have ip or modbus_port fields.
    # Serial devices are IP-invisible -- only the gateway has an IP address.

  # Multi-homed device example (additional_networks for cross-plant links):
  # - id: "your-multihomed-plc"
  #   device: "your-device-id"
  #   network: "your-primary-network"
  #   ip: "10.0.0.12"
  #   modbus_port: 5022
  #   role: "Cross-Plant PLC"
  #   register_map_variant: "your-variant-name"
  #   additional_networks:
  #     - network: "your-secondary-network"
  #       ip: "172.16.0.2"
`
