package scaffold

// Environment returns a complete environment skeleton YAML with inline documentation.
// The caller should redirect this output to a file:
//
//	ot-design scaffold --environment > design/environments/my-env/environment.yaml
func Environment() string {
	// PROTOTYPE-DEBT: [td-design-003] Schema version is hardcoded to "0.1".
	// Update this scaffold when schema v0.2 features are defined.
	return environmentScaffold
}

// environmentScaffold is the complete environment skeleton template.
// See design/environments/greenfield-water-mfg/environment.yaml for a complete example.
const environmentScaffold = `# Environment Skeleton - generated by ot-design scaffold --environment
# Save this file to: design/environments/<your-env-id>/environment.yaml
# See design/environments/greenfield-water-mfg/environment.yaml for a complete example.
# Reference: ADR-009 D5 - Environment Schema v0.1
# Reference: ADR-010 D1, D3, D4 - Archetype, era_span, and boundary extensions

# Required: must be "0.1" for the current schema version.
schema_version: "0.1"

environment:
  # Required: unique identifier, kebab-case, matches the directory name.
  id: "your-environment-id"
  # Optional: human-readable name for display in HMI or scenario descriptions.
  name: "Your Environment Name"
  # Optional: description for training context.
  description: "Brief description of this facility and its training purpose"
  # Optional: network topology classification for training context (ADR-010 D1).
  # Valid values: modern-segmented | legacy-flat | hybrid
  # modern-segmented: Purdue-model facility with VLANs and managed switches.
  # legacy-flat:      Single flat network, no segmentation between device types.
  # hybrid:           Mixed topology -- some segmentation, some flat segments.
  # archetype: "hybrid"
  # Optional: installation era of the environment, YYYY or YYYY-YYYY (ADR-010 D3).
  # Documents when the facility was built or the span of the buildout period.
  # era_span: "2020-2024"

# All networks used by any placement must be listed here.
# Each ref must match a filename in design/networks/ (without .yaml extension).
# Serial buses are networks too -- list them here even though they have no IP subnet.
networks:
  - ref: "your-ethernet-network"    # e.g., wt-level1, mfg-flat
  - ref: "your-serial-bus"          # e.g., mfg-serial-bus (omit if no serial devices)

# Placements wire device atoms onto networks with specific addressing.
# Each placement ID must be unique within this environment.
# Validate using: ot-design validate design/environments/<your-env-id>/
placements:
  # Ethernet device example (direct Modbus TCP access):
  - id: "your-plc-01"
    # Required: references a file in design/devices/ (without .yaml extension).
    device: "your-device-id"
    # Required: must be listed in the networks section above.
    network: "your-ethernet-network"
    # Required for ethernet placements: IPv4 address within the network's subnet.
    ip: "10.0.0.10"
    # Required for ethernet Modbus TCP devices: port in range 5020-5039 (per CLAUDE.md).
    modbus_port: 5020
    # Optional: human-readable role description for training context.
    role: "PLC 1 - Process Control"
    # Required if device has multiple variants: selects the register map layout.
    # Must match a key in the device's register_map_variants section.
    register_map_variant: "your-variant-name"
    # Optional: year this device was first commissioned in this facility (ADR-010 D3).
    # Valid range: 1960 to current year + 2 (to accommodate staged equipment).
    # installed: 2020

  # Gateway device example (bridges Ethernet to serial bus):
  - id: "your-gateway-01"
    device: "your-gateway-device"
    network: "your-ethernet-network"
    ip: "10.0.0.20"
    modbus_port: 5030
    role: "Serial-to-Ethernet Gateway"
    register_map_variant: "your-gateway-variant"
    # Required for gateway-category devices: list all serial networks this gateway bridges.
    bridges:
      # from_network: always the Ethernet side (the IP network the gateway is on).
      # to_network: always the serial side (the RS-485 bus the legacy devices are on).
      - from_network: "your-ethernet-network"
        to_network: "your-serial-bus"

  # Serial device example (accessed via gateway, not directly by IP):
  - id: "your-serial-plc-01"
    device: "your-serial-device"
    network: "your-serial-bus"
    # Required for serial devices: Modbus RTU address, range 1-247.
    # Address 0 is Modbus broadcast (reserved). Addresses 248-255 are reserved.
    serial_address: 1
    # Required for serial devices: must match a placement ID of a gateway device.
    gateway: "your-gateway-01"
    role: "Line A PLC"
    register_map_variant: "your-serial-variant"
    # Note: serial devices must NOT have ip or modbus_port fields.
    # Serial devices are IP-invisible -- only the gateway has an IP address.

  # Multi-homed device example (additional_networks for cross-plant links):
  # - id: "your-multihomed-plc"
  #   device: "your-device-id"
  #   network: "your-primary-network"
  #   ip: "10.0.0.12"
  #   modbus_port: 5022
  #   role: "Cross-Plant PLC"
  #   register_map_variant: "your-variant-name"
  #   additional_networks:
  #     - network: "your-secondary-network"
  #       ip: "172.16.0.2"

# Optional: boundary state declarations document network segmentation for training scenarios.
# Required when archetype is "hybrid" (ENV-026). Supported for all archetypes (ADR-010 D4).
# Each entry describes the enforced, intended, or absent boundary between two networks.
# boundaries:
#   - between: ["your-ethernet-network", "your-serial-bus"]
#     # Required: enforced | intended | absent
#     # enforced: boundary device is present and actively filtering traffic.
#     # intended: boundary is in the network design but not yet enforced in hardware.
#     # absent:   no segmentation exists between these networks (flat topology).
#     state: "enforced"
#     # Optional: type of boundary enforcement infrastructure (ADR-010 D4).
#     # Valid values: managed-switch | firewall | ids-sensor | vlan-only | other
#     infrastructure: "managed-switch"
#     # Optional: year this boundary was commissioned (valid range: 1960 to current year + 2).
#     installed: 2020
#     # Optional: human-readable context for training scenarios.
#     notes: "Level 1 to Level 2 boundary managed switch with ACL"
`
