package scaffold

// Network returns a complete network atom skeleton YAML with inline documentation.
// The skeleton contains all required fields and explanatory comments.
func Network() string {
	// PROTOTYPE-DEBT: [td-design-002] Schema version is hardcoded to "0.1".
	// Update this scaffold when schema v0.2 features are defined.
	return networkScaffold
}

// networkScaffold is the complete network atom skeleton template.
// See design/networks/wt-level1.yaml for a complete ethernet example.
// See design/networks/mfg-serial-bus.yaml for a complete serial example.
const networkScaffold = `# Network Atom Skeleton - generated by ot-design scaffold --network
# Edit all placeholder values before use.
# See design/networks/wt-level1.yaml for a complete ethernet example.
# See design/networks/mfg-serial-bus.yaml for a complete serial bus example.
# Reference: ADR-009 D4 - Network Atom Schema v0.1

# Required: must be "0.1" for the current schema version.
schema_version: "0.1"

network:
  # Required: unique identifier, kebab-case, matches the filename without .yaml
  id: "your-network-id"
  # Optional: human-readable name for display in HMI or reports
  name: "Your Network Name"
  # Required: one of: ethernet, serial-rs485, serial-rs232, serial-rs422
  # ethernet:     IP-based network (VLAN, managed/unmanaged switch)
  # serial-rs485: RS-485 multidrop bus (common for legacy PLCs: Modbus RTU, DH-485)
  # serial-rs232: RS-232 point-to-point serial (uncommon for modern OT)
  # serial-rs422: RS-422 full-duplex serial (RTU modems, flow computers)
  type: "ethernet"
  # Optional: description for training context
  description: "Brief description of this network segment and its role in the facility"

properties:
  # Required for ethernet type: CIDR subnet notation (e.g., "10.10.10.0/24").
  # Absent or omitted for serial types -- serial buses have no IP addressing.
  subnet: "10.0.0.0/24"

  # Optional: VLAN tag (present only on managed switches with VLAN configuration).
  # Omit for unmanaged switches or serial networks.
  # vlan: 10

  # Optional: whether the switch supports port configuration and management.
  # true: VLAN-capable, supports SPAN/port mirroring for passive monitoring.
  # false: unmanaged switch or serial bus -- no configuration interface.
  managed_switch: false

  # Optional: whether passive traffic capture is possible on this segment.
  # true: monitoring tool (Dragos, Zeek) can observe traffic via SPAN port.
  # false: unmanaged switch, direct cable, or serial bus -- no tap point without hardware insertion.
  span_capable: false
`
