package scaffold

// Process returns a complete process schematic skeleton YAML with inline documentation.
// The caller should redirect this output to a file:
//
//	ot-design scaffold --process > design/environments/my-env/process.yaml
func Process() string {
	// PROTOTYPE-DEBT: [td-design-004] Schema version is hardcoded to "0.1".
	// Update this scaffold when schema v0.2 features are defined.
	return processScaffold
}

// processScaffold is the complete process schematic skeleton template.
// Reference: Milestone Beta 0.5 - Process Schematic Schema
// Reference: RD-1 through RD-4 (resolved design decisions, milestone spec)
const processScaffold = `# Process Schematic Skeleton - generated by ot-design scaffold --process
# Save this file to: design/environments/<your-env-id>/process.yaml
# Reference: Milestone Beta 0.5 - Process Schematic Schema v0.1
# Reference: RD-1 (equipment vs gateway separation), RD-4 (network_context overlay)
# Cross-references placement IDs from the companion environment.yaml in the same directory.

# Required: must be "0.1" for the current schema version.
schema_version: "0.1"

process:
  # Required: unique identifier, matches the environment this process schematic belongs to.
  id: "your-environment-id"
  # Required: human-readable name for HMI display and scenario descriptions.
  name: "Your Process Schematic Name"
  # Optional: description of the process for training context.
  description: "Brief description of the physical process this schematic documents"
  # Optional: layout direction for SVG rendering. Default is "horizontal" if omitted.
  # Valid values: horizontal | vertical
  flow_direction: "horizontal"

# Stages represent sequential steps in the physical process.
# Each stage groups related equipment (e.g., intake, treatment, distribution).
stages:
  - id: "intake"
    name: "Raw Water Intake"
    # Optional: identifies the primary PLC for this stage.
    # Placement must reference a placement ID in the companion environment.yaml.
    controller:
      placement: "intake-plc-01"
      device: "compactlogix-l33er"
    equipment:
      # Equipment ID must be unique across the entire process schematic.
      - id: "raw-water-well"
        # Valid types: tank, basin, pump, valve, blower, analyzer_station, chromatograph,
        #              uv_system, clarifier, screen, compressor, meter, heat_exchanger
        # Note: "gateway" is NOT a valid equipment type -- gateways belong in network_context per RD-1.
        # Note: "basin" is distinct from "tank" (aeration basins, equalization basins).
        type: "tank"
        label: "Raw Water Well"
        # Optional: installation era year (>= 1970, <= current year). Warning if out of range.
        era: 2018
        instruments:
          - tag: "LT-101"
            name: "Raw Well Level Transmitter"
            # isa_type must match the tag prefix to satisfy PRO-019.
            # ISA-5.1 instrument prefixes: LT, FT, PT, TT, AT, AIT, PDT, ST, VT, BT, IT,
            #                              HS, ZS, ZSO, ZSC, FE
            # ISA-5.1 equipment designators: P, V, B, C, SV, GC, FM
            # Project extension (NOT ISA-5.1 standard): run (binary coil run-status)
            isa_type: "LT"
            # Placement must reference a placement ID in the companion environment.yaml.
            placement: "intake-plc-01"
            register:
              # type: "holding" or "coil"
              type: "holding"
              # address must be >= 0 and within the device atom's max_holding or max_coils capacity.
              address: 0
            unit: "m"
            # range: [min, max] engineering range for this instrument.
            range: [0.0, 5.0]
            # scale: [scale_min, scale_max] -- should match the device atom's scale_min/scale_max
            # for this register address. Mismatches generate a PRO-020 warning.
            scale: [0.0, 5.0]
            # Optional: alarm thresholds for color coding in the HMI.
            # Supports bidirectional thresholds (e.g., level transmitters need high and low alarms).
            thresholds:
              warning: 4.0      # High warning: approaching overflow
              alarm: 4.5        # High alarm: overflow imminent
              warning_low: 1.0  # Low warning: approaching pump cavitation threshold
              alarm_low: 0.5    # Low alarm: pump cavitation risk

      - id: "intake-pump-01"
        type: "pump"
        label: "Intake Pump 1"
        era: 2018
        instruments:
          - tag: "run-P-101"
            name: "Intake Pump 1 Run Status"
            # "run" is a project extension for binary coil run-status -- NOT standard ISA-5.1.
            isa_type: "run"
            placement: "intake-plc-01"
            register:
              type: "coil"
              address: 0
            unit: "bool"

      - id: "travelling-screen-01"
        type: "screen"
        label: "Travelling Debris Screen"
        era: 2015
        instruments:
          - tag: "ZSC-101"
            name: "Screen Wash Active"
            isa_type: "ZSC"
            placement: "intake-plc-01"
            register:
              type: "coil"
              address: 2
            unit: "bool"

  - id: "treatment"
    name: "Water Treatment"
    controller:
      placement: "treatment-plc-01"
      device: "compactlogix-l33er"
    equipment:
      - id: "sand-filter-01"
        type: "tank"
        label: "Sand Filter"
        era: 2018
        instruments:
          - tag: "PDT-201"
            name: "Filter Differential Pressure"
            isa_type: "PDT"
            placement: "treatment-plc-01"
            register:
              type: "holding"
              address: 2
            unit: "kPa"
            range: [0.0, 50.0]
            scale: [0.0, 50.0]
            thresholds:
              warning: 15.0  # Backwash trigger threshold
              alarm: 25.0    # Elevated backwash urgency

      - id: "uv-system-01"
        type: "uv_system"
        label: "UV Sterilization System"
        era: 2020
        instruments:
          - tag: "AT-201"
            name: "UV Lamp Intensity"
            isa_type: "AT"
            placement: "treatment-plc-01"
            register:
              type: "holding"
              address: 3
            unit: "mW/cm2"
            range: [0.0, 100.0]
            scale: [0.0, 100.0]
            thresholds:
              warning_low: 30.0  # Low intensity warning
              alarm_low: 20.0    # Low intensity alarm (disinfection at risk)

# Connections document physical process flow between equipment.
# Only physical process connections are listed here.
# Serial bus topology and WAN/wireless links belong in network_context (per RD-1 and RD-4).
# type: "pipe" (fluid or gas transfer) or "duct" (air delivery from blower to diffusers)
connections:
  - from: "raw-water-well"
    to: "intake-pump-01"
    type: "pipe"
    label: "Raw water intake"
  - from: "intake-pump-01"
    to: "sand-filter-01"
    type: "pipe"
    label: "Raw water to treatment"
  - from: "sand-filter-01"
    to: "uv-system-01"
    type: "pipe"
    label: "Filtered water to UV"

# Optional: security-relevant network element overlay (RD-4).
# Documents network context elements that are visible from the process schematic.
# Placement references are optional (use for elements that map to a gateway device in the environment).
# network_context:
#   - id: "cellular-gateway"
#     # type: wan_link | internet_gateway | wireless_bridge
#     type: "wan_link"
#     label: "Cellular WAN Link"
#     era: 2021
#     # Optional: references a placement ID in the companion environment.yaml (warning if not found).
#     placement: "cradlepoint-ibr600-01"
#     warning: "Unencrypted vendor remote access path"
#     notes: "Blower vendor reads run_hours register via this link for predictive maintenance scheduling"
`
